name: Create or Update Latest Tag and Build

on:
  push:
    branches:
      - master

jobs:
  create-or-update-latest-tag-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Change this to your desired Node.js version

      - name: Install Dependencies
        run: npm install  # Use yarn install or your preferred package manager

      - name: Build
        run: npm run build  # Replace with your build command

      - name: Copy dist content
        run: mv dist/* . && rm -rf dist

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* *node_modules* *__tests__* *.idea* *example* *.eslintrc.js *.prettierc *jest.config.js *package-lock.json *tsconfig.build.json *tsconfig.json'
